name: Python Environment

on:
  # To run manually
  workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
    
    - name: Install Python dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -U setuptools wheel
        python -m pip install awscli matplotlib scipy m3u8 git+https://github.com/kkroening/ffmpeg-python
    
    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg

    - name: Hello world 
      run: |
        python -c "import scipy as sp; print('Scipy version: '+sp.__version__)"
        python -c "import matplotlib as mpl; print('Matplotlib version: '+mpl.__version__)"
